---
apiVersion: v2
appVersion: 4.3.0 # renovate: depName=ghcr.io/k8snetworkplumbingwg/multus-cni datasource=docker
description: multus CNI allows multiple NICs per pod
name: multus
version: 7.0.0
kubeVersion: ">=1.16.0-0"
keywords:
  - multus
home: https://github.com/angelnu/helm-charts/tree/master/charts/stable/multus
icon: https://raw.githubusercontent.com/k8snetworkplumbingwg/multus-cni/master/docs/images/Multus.png
sources:
  - https://github.com/k8snetworkplumbingwg/multus-cni
maintainers:
  - name: angelnu
    email: git@angelnu.com
dependencies:
  - name: common
    repository: https://bjw-s-labs.github.io/helm-charts
    version: 5.0.1

annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: |
        **BREAKING**:
        Updated common library to 5.0.1, which includes a breaking change to the way rawResources are defined. Please see the [common library documentation](
