---
name: "Docs: Release to GitHub pages"

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/docs-release.yaml"
      - ".ci/mkdocs/mkdocs.yml"
      - "docs/**"

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  build-docs:
    name: Build documentation
    runs-on: ubuntu-24.04
    permissions:
      contents: write
    steps:
      - name: Checkout main branch
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false

      - name: Install Mise and required tools
        uses: jdx/mise-action@dba19683ed58901619b14f395a24841710cb4925 # v4.1.0
        with:
          cache: false

      - name: Build and publish docs
        run: |
          source .venv/bin/activate
          mkdocs build -f .ci/mkdocs/mkdocs.yml

      - name: Deploy
        uses: peaceiris/actions-gh-pages@84c30a85c19949d7eee79c4ff27748b70285e453 # v4.1.0
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
          destination_dir: docs

  publish-docs:
    name: Publish documentation
    runs-on: ubuntu-24.04
    needs:
      - build-docs
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout main branch
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          path: src
          persist-credentials: false

      - name: Checkout gh-pages branch
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          ref: gh-pages
          path: gh-pages
          persist-credentials: false

      - name: Deploy to GitHub Pages
        uses: ./src/.github/actions/publish-folder-to-pages
        with:
          path: gh-pages/
          deleteArtifactAfterPublish: true
