name: "Pre-commit consistency check"

on:
  workflow_call:
    inputs:
      modifiedFiles:
        description: >
          A JSON encoded array of files to check
        required: true
        type: string

jobs:
  pre-commit-check:
    name: Run pre-commit checks
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run against changes
        uses: pre-commit/action@v3.0.1
        with:
          extra_args: --files ${{ join(fromJson(inputs.modifiedFiles), ' ') }} --config .ci/pre-commit/config.yaml
