name: "Pre-commit consistency check"

on:
  workflow_call:
    inputs:
      modifiedFiles:
        description: >
          A JSON encoded array of files to check
        required: true
        type: string

env:
  # renovate: datasource=github-releases depName=norwoodj/helm-docs
  HELM_DOCS_VERSION: "v1.11.0"

jobs:
  pre-commit-check:
    name: Run pre-commit checks
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: install helm-docs
        run: |
          cd /tmp
          wget https://github.com/norwoodj/helm-docs/releases/download/v${{env.HELM_DOCS_VERSION}}/helm-docs_${{env.HELM_DOCS_VERSION}}_Linux_x86_64.tar.gz
          tar -xvf helm-docs_${{env.HELM_DOCS_VERSION}}_Linux_x86_64.tar.gz
          sudo mv helm-docs /usr/local/sbin

      - name: Run against changes
        uses: pre-commit/action@v3.0.0
        with:
          extra_args: --files ${{ join(fromJson(inputs.modifiedFiles), ' ') }} --config .ci/pre-commit/config.yaml
